import textcase
from dataclasses import dataclass
from test.constants.shared import FieldType

@dataclass
class FieldMapping:
    selector: str
    field_type: str

# Base form selector that scopes all fields.
FORM_SELECTOR = "form#account-create"

class RegistrationField:
    """
    Encapsulates all registration form field mappings.

    Every field is automatically scoped to the parent form, ensuring that
    every selector references the correct element. The auto-generated dictionary
    (via get_all_fields()) converts attribute names into camelCase keys for consistency.
    """
    FORM_SELECTOR = FORM_SELECTOR

    # UI field mappings
    TITLE_CODE = FieldMapping(selector=f"{FORM_SELECTOR} #titleCode", field_type=FieldType.DROPDOWN)
    FIRST_NAME = FieldMapping(selector=f"{FORM_SELECTOR} #firstName", field_type=FieldType.STRING)
    LAST_NAME = FieldMapping(selector=f"{FORM_SELECTOR} #lastName", field_type=FieldType.STRING)
    DATE_OF_BIRTH = FieldMapping(
        # Even though this might be an XPath, we include the parent scope consistently.
        selector=f"{FORM_SELECTOR} //div[@class='form-block text-input-block date-picker-wrapper']//input",
        field_type=FieldType.DATE
    )
    EMAIL = FieldMapping(selector=f"{FORM_SELECTOR} #email", field_type=FieldType.STRING)
    POSTAL_CODE = FieldMapping(selector=f"{FORM_SELECTOR} #postalCode", field_type=FieldType.NUMBER)
    CITY = FieldMapping(selector=f"{FORM_SELECTOR} #city", field_type=FieldType.STRING)
    STREET = FieldMapping(selector=f"{FORM_SELECTOR} #street", field_type=FieldType.STRING)
    HOUSE_NUMBER = FieldMapping(selector=f"{FORM_SELECTOR} #houseNumber", field_type=FieldType.NUMBER)
    ADDRESS = FieldMapping(selector=f"{FORM_SELECTOR} #Address", field_type=FieldType.STRING)
    PASSWORD = FieldMapping(selector=f"{FORM_SELECTOR} #password", field_type=FieldType.STRING)
    PASSWORD_REPEAT = FieldMapping(selector=f"{FORM_SELECTOR} #passwordRepeat", field_type=FieldType.STRING)
    MARKETING_CONSENT = FieldMapping(
        selector=f"{FORM_SELECTOR} label[for='CZ_MARKETING_CONSENT']",
        field_type=FieldType.CHECKBOX
    )
    REGISTRATION_CONSENT = FieldMapping(
        selector=f"{FORM_SELECTOR} label[for='CZ_REGISTRATION_CONSENT']",
        field_type=FieldType.CHECKBOX
    )

    @classmethod
    def get_all_fields(cls) -> dict:
        """
        Dynamically generates and returns a dictionary of all field mappings.
        The keys are generated by converting the attribute names (in snake_case)
        into camelCase using the shared textcase library.
        """
        return {
            attr_name.lower(): attr_value  # Simple lower-case conversion.
            for attr_name, attr_value in cls.__dict__.items()
            if isinstance(attr_value, FieldMapping)
        }